name: urban-api

services:
  database:
    container_name: ${POSTGRES_CONTAINER_NAME:-urban_db}
    image: postgis/postgis:16-3.4
    restart: on-failure
    ports:
      - ${EXPORT_POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    env_file:
      - ./db.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d postgres
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  migrator:
    container_name: migrator
    build:
      context: ../urban_db
      dockerfile: migrations.Dockerfile
    env_file:
      - ./.env
    environment:
      - DEBUG
    depends_on:
      database:
        condition: service_healthy

  # unused anyway

  # keycloak:
  #   container_name: keycloak
  #   image: quay.io/keycloak/keycloak:20.0.2
  #   command:
  #     - start --db postgres --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
  #   ports:
  #     - ${EXPORT_KC_PORT:-8080}:${KC_PORT:-8080}
  #   env_file:
  #     - ./keycloak.env
  #   volumes:
  #     - ./kc_data:/opt/keycloak/data/
  #     - type: bind
  #       source: ./kc_data/import/realm-export.json
  #       target: /opt/keycloak/data/import/realm-export.json
  #       read_only: true
  #   depends_on:
  #     migrator:
  #       condition: service_completed_successfully
  #   healthcheck:
  #     test: curl -f http://localhost:8080/realms/master || exit 1
  #     start_period: 10s
  #     interval: 30s
  #     retries: 3
  #     timeout: 5s
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "200k"
  #       max-file: "10"

  api:
    container_name: urban_api
    build:
      context: ..
      dockerfile: urban_api/Dockerfile
    restart: on-failure
    ports:
      - ${EXPORT_API_PORT:-8000}:${PORT:-8000}
    env_file:
      - ./.env
    environment:
      - DEBUG
    depends_on:
      # keycloak:
      #   condition: service_healthy
      migrator:
        condition: service_completed_successfully
    healthcheck:
      test: curl -f http://localhost:8000/health_check/ping
      interval: 10s
      timeout: 5s
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
